import { toEnum } from "./utils/toEnum";

export const ValidCssValue = toEnum(["string", "number", "Symbol"]);

export const ValidStyleKeys = toEnum(["@default", "@tablet", "@phone"]);

export const ValidStyleableProps = toEnum([
    "align",
    "background",
    "bgcolor",
    "border",
    "color",
    "height",
    "valign",
    "width",
    "fontFamily",
    "fontSize",
    "backgroundColor",
    "colSpan",
    "frameBorder",
    "marginHeight",
    "marginWidth",
    "muted",
    "rowSpan",
    "wrap",
    "hspace",
    "nowrap",
    "size",
    "vspace",
    "maxWidth",
    "minWidth",
    "maxHeight",
    "minHeight",
    "background"
]);

export const ValidPrimitives = toEnum([
    "a",
    "body",
    "table",
    "head",
    "body",
    "html",
    "div",
    "span",
    "ul",
    "ol",
    "li",
    "hr",
    "td",
    "tr",
    "hr",
    "img",
    "p",
    "style"
]);

export const ValidPseudos = toEnum([
    ":active",
    ":after",
    ":any-link",
    ":before",
    ":blank",
    ":checked",
    ":default",
    ":defined",
    ":disabled",
    ":empty",
    ":enabled",
    ":first",
    ":first-child",
    ":first-letter",
    ":first-line",
    ":first-of-type",
    ":focus",
    ":focus-visible",
    ":focus-within",
    ":fullscreen",
    ":hover",
    ":in-range",
    ":indeterminate",
    ":invalid",
    ":last-child",
    ":last-of-type",
    ":left",
    ":link",
    ":only-child",
    ":only-of-type",
    ":optional",
    ":out-of-range",
    ":placeholder-shown",
    ":read-only",
    ":read-write",
    ":required",
    ":right",
    ":root",
    ":scope",
    ":target",
    ":valid",
    ":visited"
]);
