import { strEnum } from "../utils/enums";

export const CssStyleablePropertiesKind = strEnum([
    "align",
    "background",
    "bgcolor",
    "border",
    "color",
    "height",
    "valign",
    "width",
    "fontFamily",
    "fontSize",
    "backgroundColor",
    "colSpan",
    "frameBorder",
    "marginHeight",
    "marginWidth",
    "muted",
    "rowSpan",
    "wrap",
    "hspace",
    "nowrap",
    "size",
    "vspace",
]);
