import { strEnum } from "../utils/enums";
export const CssPseudoKind = strEnum([
    "::after",
    "::backdrop",
    "::before",
    ":active",
    ":after",
    ":any-link",
    ":before",
    ":blank",
    ":checked",
    ":default",
    ":defined",
    ":disabled",
    ":empty",
    ":enabled",
    ":first",
    ":first-child",
    ":first-letter",
    ":first-line",
    ":first-of-type",
    ":focus",
    ":hover",
    ":last-child",
    ":last-of-type",
    ":root",
    ":scope",
    ":target",
    ":visited",
]);
//# sourceMappingURL=CssPseudos.js.map