import { toEnum } from "../../utils";

export const StyleablePropertiesKind = toEnum([
    "align",
    "background",
    "bgcolor",
    "border",
    "color",
    "height",
    "valign",
    "width",
    "fontFamily",
    "fontSize",
    "backgroundColor",
    "colSpan",
    "frameBorder",
    "marginHeight",
    "marginWidth",
    "muted",
    "rowSpan",
    "wrap",
    "hspace",
    "nowrap",
    "size",
    "vspace",
    "maxWidth",
    "minWidth",
    "maxHeight",
    "minHeight",
]);
